### ISSUE TITLE
Seems not to be working on nougat.

### ISSUE THREAD

**Issue by drickles** [chylek/FakeWifi#4]
I first tried it with the unofficial nougat xposed framework but it didn't work so I thought it was because that version of xposed wasn't complete. But the official xposed support for android dropped and it still doesn't seem to work. I tried it on the asphalt extreme game and it didn't work. Also tried it on the Twitter app to see if videos will auto play like how it does when wifi is on and it didn't work too. Can you please take a look at this problem too?

**Comment by chylek** [comment]
hi, thanks for the report. Now that xposed is officially available on nougat, I will finally be able to test the app on it. 
Right now it looks like the fix will not be straightforward, so please be patient, I will let you know when I've fixed it.

**Comment by chylek** [comment]
Hi, I've fixed some issues on Nougat, but I am not sure whether they were the same as yours. Could you try this https://www.dropbox.com/s/e5dhjpt469ohz9l/app-release.apk?dl=1 version and tell me if your problems are fixed?

**Comment by drickles** [comment]
Sorry for the late reply. Trying it now. Will let you know how it goes. Thank you

**Comment by drickles** [comment]
Well infortunately it still doesn't seem to work. Which courses me to suspect that the problem might be somehow internal. I'm on a stock custom Rom. Touchwiz to be precise. And as we all know Rom modifications are limited on stock roms. I'm suspecting your app may just have landed on the long list of apps that just won't work on stock roms. I'll try the app on a pure nougat custom rom to test out my hypothesis

**Comment by chylek** [comment]
I'm sorry to hear that it's still not working. I've tried only the Twitter app and for me it worked as expected. There shouldn't be much difference in stock rom vs lineageos I am using. 
If you are willing to troubleshoot this a bit more, then there is an app you can try that gives a basic info about active wifi connections: https://github.com/lemonsqueeze/FakeWifiConnection/raw/master/TestWifi/bin/TestWifi.apk 

Just to be sure:
* you should have an active connection to the internet - either using mobile data plan or ethernet cable.
* Fake Wifi should be active ("ticked") in Xposed Installer - Modules 
1. Activate Fake Wifi in Xposed Installer
1. Reboot your device. 
1. Install Test Wifi apk
1. Open the Fake Wifi app
1. Make sure that "Main switch" is active
1. To be absolutely sure, use "Select all" (in the menu) to fake the wifi for all available apps. 
1. reboot your device again 
1. run the Test Wifi app and check whether faked SSID and MAC are being shown

**Comment by drickles** [comment]
Owk so apparently I followed the steps you gave me and it started working. So I don't know what default values were placed in the fake wifi app to mock the original mac and ssid but after doing everything and opening the test wifi apk I found out no values were showing at all. Not my original mac and ssid. And definitely not the default values you intended your app to mock mine with. Which caused me to believe that your app was masking my Wi-Fi connection alright. Just that there were null default values. So I just went to the app settings and placed it some custom ssid and mac address I got online and voila. It worked. That's very much for your patience and in helping me fix this. I really needed it to work. It's a very great up and comes in handy a lot.
