### ISSUE TITLE
Not working on One Plus 3

### ISSUE THREAD

**Issue by jo45** [chylek/FakeWifi#8]
Hello.

The module does not seem to work one One Plus 3.
Everything is looking fine, no error or anything, but wifi is not faked on any apps. Tried rebooting and faking all apps, still nothing.

Configuration:
Android 7.0
Magisk 16.0
Xposed 89.2 (systemless) installed via Magisk
Xposed installer 3.1.15 (installed from Magisk)

**Comment by chylek** [comment]
Hello,
in theory, it should work without a problem. You didn't mention what you are trying to achieve, but let's troubleshoot this a bit more. 
Here is an app you can try that gives a basic info about active wifi connections: https://github.com/lemonsqueeze/FakeWifiConnection/raw/master/TestWifi/bin/TestWifi.apk

Just to be sure:

-    you should have an active connection to the internet - either using mobile data plan or ethernet cable.
-    Fake Wifi should be active ("ticked") in Xposed Installer - Modules

1.    Activate Fake Wifi in Xposed Installer
1.    Reboot your device.
1.    Install Test Wifi apk
1.    Open the Fake Wifi app
1.    Make sure that "Main switch" is active
1.    To be absolutely sure, use "Select all" (in the menu) to fake the wifi for all available apps.
    reboot your device again
1.    run the Test Wifi app and check whether faked SSID and MAC are being shown

**Comment by ffse361** [comment]
Followed directions (checked all apps and activated the module)
Same Problem and Test Wifi App crashes immediately.

Exposed v89
Android 7.1.2
Huawei Y5, arm

**Comment by ffse361** [comment]
My phone crashed when I turned wifi or 4G on. I unchecked the Fake Wifi in Xposed and now USB Tethering asked for a VPN connection. I didn't at first.
Probably because I selected Mode 1 in USB Tethering..

**Comment by chylek** [comment]
Does the Test Wifi app crash even when the Fake Wifi is not active?

**Comment by ffse361** [comment]
Yes, even then. But fortunately my initial problem with USB Tethering is solved by selecting mode 1 in options. Google Play and Whatsapp work now.

**Comment by xelemorf** [comment]
I have the same issue on OnePlus3 On Marshmallow (OxygenOS 3.2.8):
Normal Browsing works, but Google Play downloads are not working (Google Play browsing works), Xposed Framework downloads also not working.

I have only activated the module, did not select any apps, disabling the module with main switch and restart does not resolve, deactivating and rebooting also does not resolve, aftereards uninstall and reboot also does not resolve the problem. Clearing the cache for download manager also did not helped, so stuck with downloads not working (doh!), need to restore a clean nand backup.
Please add into the description of the module: Not working on Marshmallow

**Comment by chylek** [comment]
Hi @xelemorf ,
the app works on Marshmallow. In fact, that's the only truly tested platform as I use it daily on MM.
The app also doesn't do any permanent changes to the system so deactivating the module in xposed or uninstalling the app should suffice to revert any changes.
